// Copyright 2019 Profects Group B.V.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gormetrics

// ErrDbIsNil is the error generated by gormetrics if an error occurs when
// creating a gormetrics plugin instance with a nil plugin.
const ErrDbIsNil gormetricsErr = "db is nil"

// A simple type for constant errors. Makes errors easy to match.
type gormetricsErr string

// Error returns the value as a string.
func (e gormetricsErr) Error() string {
	return string(e)
}
