package gormetrics

// ErrDbIsNil is the error generated by gormetrics if an error occurs when
// creating a gormetrics plugin instance with a nil plugin.
const ErrDbIsNil gormetricsErr = "db is nil"

// A simple type for constant errors. Makes errors easy to match.
type gormetricsErr string

// Error returns the value as a string.
func (e gormetricsErr) Error() string {
	return string(e)
}
